# crontab.ugly:
# Timed tasks for FixMyTransport site. Template file.
#
# Copyright (c) 2010 UK Citizens Online Democracy. All rights reserved.
# Email: louise@mysociety.org. WWW: http://www.mysociety.org/
#
# 

PATH=/usr/local/bin:/usr/bin:/bin
MAILTO=team@fixmytransport.com

# Every 5 minutes
*/5 * * * * !!(*= $user *)!! run-with-lockfile -n /data/vhost/!!(*= $vhost *)!!/send-problem-reports.lock /data/vhost/!!(*= $vhost *)!!/fixmytransport/script/send-problem-reports || echo "stalled?"